name: AArmor
main: laith98\AutoArmor\Main
version: "0.0.1"
api: [3.0.0]
author: Laith98 (Hypixel PE Dev) 
description: "AutoArmor The plugin is to help with wearing armor because armor cannot be worn quickly, so it can be worn quickly and easily, For Pocketmine Servers"
